### ISSUE TITLE
giving it a try but not taking my longitude W

### ISSUE THREAD

**Issue by ghost** [tedsluis/dump1090.socket30003#1]
my location is N50.022, W114.433, 
I entered 50.0222, -114,422... it doesn't like the negative sign it seems.

Thanks,
Dino

**Comment by tedsluis** [comment]
Hi Dino,

Although I use github for quite some time (just for using stuff from others), committing source code to my own repro is new to me. I did not notice that you had opened an "issue" (and closed it) and there are probably lots of other things I have to learn.

I program a lot (in Perl and Bash, without access to the internet) and I'm actually quite pleased that I am now learning how to use github ;-)

If I had seen your "issue" earlier I would have seen what the problem was right away ;-) How every, I found your github email in my spam box, two days later ;-( All github email ended in my spam box, but I have now fixed that too!

Thanks,

Ted

**Comment by ghost** [comment]
Hi Ted,
Thanks for the reply. No worries about not noticing the issue. I, too, am new to github so I fully understand. 

I realize that this is probably a hobby for most of us on the board so my expectations reflect the fact that there are many other things that take up our time.

I'm enjoying this subject very much since it combines my passion for flight and programming even if it's only as an amateur.

Thank you for your contributions!

Cheers,
Dino
